# Generated by Django 5.1.2 on 2024-11-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='receiver_adress',
            new_name='receiver_address',
        ),
    ]
